version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

sphinx:
   configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
